This source code created by IndianAIProduction.com team https://indianaiproduction.com/horse-or-human-prediction-using-convolutional-neural-network

Video on 

Part-1: https://youtu.be/i8gwTMoAtiY

Part2: https://youtu.be/C6CxoMtNkJo

Part3: https://youtu.be/lyDGt1KdFB4

Part4: https://youtu.be/sssusl3XILs

Part5: https://youtu.be/dS12-YHUM-Q

Part6: https://youtu.be/qdQaMLj4yo8


for video tutorial visit our youtube channel www.youtube.com\IndianAIProduction


# Predict Horse or Human

Here we are loading train CNN model to predict Given input (image) is Horse of Human

# Import Libraries

In [ ]:
# Load Liraries
import numpy as np

import keras 
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


# Import Model

In [ ]:
model_path1 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/horse_human_cnn_model_new.h5' #new model.ipynb
model_path2 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/horse_human_cnn_model_v2.h5' #v2 solve overfitting Horse_or_human Classification using CNN.ipynb
model_path3 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/horse_human_cnn_model_v2_1.h5' #v2 solve overfitting Horse_or_human Classification using CNN.ipynb

model1 = keras.models.load_model(model_path1)
model2 = keras.models.load_model(model_path2)
model3 = keras.models.load_model(model_path3)


#Preprocessing

In [ ]:
#horse image path
h1 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/horse_test/horse1-204.png'
h2 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/horse_test/horse2-069.png'
h3 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/horse_test/horse3-070.png'
h4 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/horse_test/horse4-439.png'
h5 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/horse_test/horse5-203.png'
h6 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/horse_test/horse6-161.png'
h7 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/validation/horses/horse2-224.png'
h8 ="/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/validation/horses/horse5-123.png"

#human image path
hu1 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/human_test/valhuman01-09.png'
hu2 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/human_test/valhuman02-18.png'
hu3 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/human_test/valhuman03-23.png'
hu4 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/human_test/valhuman04-24.png'
hu5 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/test_data/human_test/valhuman05-19.png'
hu6 = '/content/drive/My Drive/My ML Project /DL Project/CNN/horse-or-human/dataset/validation/humans/valhuman01-13.png'

In [ ]:
import numpy as np
from keras.preprocessing import image

def pred_human_horse(model, horse_or_human):
  test_image = image.load_img(horse_or_human, target_size = (150, 150))
  test_image = image.img_to_array(test_image)/255
  test_image = np.expand_dims(test_image, axis = 0)

  result = model.predict(test_image).round(3)

  pred = np.argmax(result)
  print(result, "--->>>", pred)

  if pred == 0:
    print('Predicted>>> Horse')
  else:
    print('Predicted>>> Human')

## Predict Output

In [ ]:
for horse_or_human in [h1,h2,h3,h4,h5,h6,h7,h8, hu1,hu2,hu3,hu4,hu5,hu6]:
  pred_human_horse(model1, horse_or_human)

[[0.996 0.004]] --->>> 0
Predicted>>> Horse
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0.999 0.001]] --->>> 0
Predicted>>> Horse
[[0.586 0.414]] --->>> 0
Predicted>>> Horse
[[0.967 0.033]] --->>> 0
Predicted>>> Horse
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0.681 0.319]] --->>> 0
Predicted>>> Horse
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human


In [ ]:
for horse_or_human in [h1,h2,h3,h4,h5,h6,h7,h8, hu1,hu2,hu3,hu4,hu5,hu6]:
  pred_human_horse(model2, horse_or_human)

[[0.529 0.488]] --->>> 0
Predicted>>> Horse
[[0.529 0.536]] --->>> 1
Predicted>>> Human
[[0.62  0.398]] --->>> 0
Predicted>>> Horse
[[0.651 0.404]] --->>> 0
Predicted>>> Horse
[[0.6   0.427]] --->>> 0
Predicted>>> Horse
[[0.534 0.536]] --->>> 1
Predicted>>> Human
[[0.536 0.496]] --->>> 0
Predicted>>> Horse
[[0.527 0.504]] --->>> 0
Predicted>>> Horse
[[0.519 0.533]] --->>> 1
Predicted>>> Human
[[0.52  0.546]] --->>> 1
Predicted>>> Human
[[0.531 0.563]] --->>> 1
Predicted>>> Human
[[0.508 0.565]] --->>> 1
Predicted>>> Human
[[0.5   0.571]] --->>> 1
Predicted>>> Human
[[0.522 0.54 ]] --->>> 1
Predicted>>> Human


In [ ]:
for horse_or_human in [h1,h2,h3,h4,h5,h6,h7,h8, hu1,hu2,hu3,hu4,hu5,hu6]:
  pred_human_horse(model3, horse_or_human)

[[0.985 0.015]] --->>> 0
Predicted>>> Horse
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0.999 0.001]] --->>> 0
Predicted>>> Horse
[[0.253 0.747]] --->>> 1
Predicted>>> Human
[[0.925 0.075]] --->>> 0
Predicted>>> Horse
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0.06 0.94]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human


## Ab milenge next tutorial me,Tab tak ke liye SIKHATE SIKHATE kuch IMPLEMENT karte raho, Thank You.....-:)